# Generated by Django 5.0.4 on 2025-07-12 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odoo_app', '0004_alter_item_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='terms_and_condition',
            field=models.BooleanField(default=False),
        ),
    ]
