# Generated by Django 5.0.4 on 2025-07-12 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odoo_app', '0006_item_category_item_condition_item_size_item_tags_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
