# Generated by Django 5.0.4 on 2025-07-12 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odoo_app', '0007_alter_user_is_superuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='item',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('pending', 'Pending'), ('swapped', 'Swapped')], default='pending', max_length=20),
        ),
    ]
